#pragma once

struct SearchType {
    const wchar_t* label;
    const char* key;
    const char* value;
};

static const SearchType kPlaceTypes[] = {
    {L"Restaurant", "amenity", "restaurant"},
    {L"Cafe", "amenity", "cafe"},
    {L"Fast Food", "amenity", "fast_food"},
    {L"Bar", "amenity", "bar"},
    {L"Pub", "amenity", "pub"},
    {L"Food Court", "amenity", "food_court"},
    {L"Ice Cream", "amenity", "ice_cream"},
    {L"Hospital", "amenity", "hospital"},
    {L"Clinic", "amenity", "clinic"},
    {L"Doctors", "amenity", "doctors"},
    {L"Dentist", "amenity", "dentist"},
    {L"Pharmacy", "amenity", "pharmacy"},
    {L"Veterinary", "amenity", "veterinary"},
    {L"School", "amenity", "school"},
    {L"College", "amenity", "college"},
    {L"University", "amenity", "university"},
    {L"Library", "amenity", "library"},
    {L"Kindergarten", "amenity", "kindergarten"},
    {L"Bank", "amenity", "bank"},
    {L"ATM", "amenity", "atm"},
    {L"Post Office", "amenity", "post_office"},
    {L"Police", "amenity", "police"},
    {L"Fire Station", "amenity", "fire_station"},
    {L"Fuel", "amenity", "fuel"},
    {L"Charging Station", "amenity", "charging_station"},
    {L"Parking", "amenity", "parking"},
    {L"Bus Station", "amenity", "bus_station"},
    {L"Taxi", "amenity", "taxi"},
    {L"Toilets", "amenity", "toilets"},
    {L"Marketplace", "amenity", "marketplace"},
    {L"Cinema", "amenity", "cinema"},
    {L"Theatre", "amenity", "theatre"},
    {L"Nightclub", "amenity", "nightclub"},
    {L"Community Centre", "amenity", "community_centre"},
    {L"Supermarket", "shop", "supermarket"},
    {L"Convenience Store", "shop", "convenience"},
    {L"Bakery", "shop", "bakery"},
    {L"Butcher", "shop", "butcher"},
    {L"Greengrocer", "shop", "greengrocer"},
    {L"Seafood", "shop", "seafood"},
    {L"Department Store", "shop", "department_store"},
    {L"Mall", "shop", "mall"},
    {L"Clothes", "shop", "clothes"},
    {L"Shoes", "shop", "shoes"},
    {L"Jewelry", "shop", "jewelry"},
    {L"Beauty", "shop", "beauty"},
    {L"Hairdresser", "shop", "hairdresser"},
    {L"Electronics", "shop", "electronics"},
    {L"Mobile Phone", "shop", "mobile_phone"},
    {L"Computer", "shop", "computer"},
    {L"Hardware", "shop", "hardware"},
    {L"Furniture", "shop", "furniture"},
    {L"Books", "shop", "books"},
    {L"Stationery", "shop", "stationery"},
    {L"Toy Shop", "shop", "toys"},
    {L"Florist", "shop", "florist"},
    {L"Laundry", "shop", "laundry"},
    {L"Hotel", "tourism", "hotel"},
    {L"Guest House", "tourism", "guest_house"},
    {L"Motel", "tourism", "motel"},
    {L"Hostel", "tourism", "hostel"},
    {L"Museum", "tourism", "museum"},
    {L"Attraction", "tourism", "attraction"},
    {L"Artwork", "tourism", "artwork"},
    {L"Information", "tourism", "information"},
    {L"Park", "leisure", "park"},
    {L"Garden", "leisure", "garden"},
    {L"Playground", "leisure", "playground"},
    {L"Sports Centre", "leisure", "sports_centre"},
    {L"Fitness Centre", "leisure", "fitness_centre"},
    {L"Pitch", "leisure", "pitch"},
    {L"Stadium", "leisure", "stadium"},
    {L"Swimming Pool", "leisure", "swimming_pool"},
    {L"Office Company", "office", "company"},
    {L"Office Government", "office", "government"},
    {L"Office Lawyer", "office", "lawyer"},
    {L"Office Accountant", "office", "accountant"},
    {L"Office Insurance", "office", "insurance"},
    {L"Healthcare Hospital", "healthcare", "hospital"},
    {L"Healthcare Clinic", "healthcare", "clinic"},
    {L"Healthcare Dentist", "healthcare", "dentist"},
    {L"Healthcare Doctor", "healthcare", "doctor"},
    {L"Healthcare Pharmacy", "healthcare", "pharmacy"}
};

static constexpr int kPlaceTypeCount = sizeof(kPlaceTypes) / sizeof(kPlaceTypes[0]);